version: "2"

services:
  db:
    image: cyliconvalley.azurecr.io/postgres:10.2-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: eventtoolbox
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db-data:/var/lib/postgresql/data

  redis:
    image: cyliconvalley.azurecr.io/redis:alpine
    restart: always

  app:
    image: cyliconvalley.azurecr.io/eventtoolbox:latest
    restart: always
    build:
      context: .
    ports:
      - "80:80"
      - "443:443"
    environment:
      REDIS_URL: redis://redis:6379
      DATABASE_URL: postgresql://postgres:${POSTGRES_PASSWORD}@db/eventtoolbox
      BASE_URL: ${BASE_URL}
      ADMIN_USER: ${ADMIN_USER}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

volumes: 
   db-data: